/**
* monitor API generated from monitor.yang
*
* NOTE: This file is auto generated by polycube-codegen
* https://github.com/polycube-network/polycube-codegen
*/


// TODO: Modify these methods with your own implementation


#include "Stats.h"
#include "Monitor.h"


Stats::Stats(Monitor &parent, const StatsJsonObject &conf)
    : StatsBase(parent) {
}

Stats::~Stats() {}

uint64_t Stats::getTcpattemptfails() {
  throw std::runtime_error("Stats::getTcpattemptfails: Method not implemented");
}

uint64_t Stats::getTcpoutrsts() {
  throw std::runtime_error("Stats::getTcpoutrsts: Method not implemented");
}

uint64_t Stats::getDeliverration() {
  throw std::runtime_error("Stats::getDeliverration: Method not implemented");
}

uint64_t Stats::getResponseratio() {
  throw std::runtime_error("Stats::getResponseratio: Method not implemented");
}

uint64_t Stats::getTimestamp() {
  throw std::runtime_error("Stats::getTimestamp: Method not implemented");
}


