/**
* helloworld API
* Helloworld Service
*
* OpenAPI spec version: 2.0
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/polycube-network/swagger-codegen.git
* branch polycube
*/


/* Do not edit this file manually */

#include "api/HelloworldApiImpl.h"
#define MANAGER_TYPE io::swagger::server::api::HelloworldApiImpl
#define SERVICE_DESCRIPTION "Helloworld Service"
#define SERVICE_VERSION "2.0"
#define SERVICE_PYANG_GIT ""
#define SERVICE_SWAGGER_CODEGEN_GIT "c757d44b71d48df9e381fc8d35ea69bd12268127/c757d44"
#define SERVICE_REQUIRED_KERNEL_VERSION "4.14.0"

const std::string SERVICE_DATA_MODEL = R"POLYCUBE_DM(
module helloworld {
  yang-version 1.1;
  namespace "http://polycube.network/helloworld";
  prefix "helloworld";

  import polycube-base { prefix "basemodel"; }

  organization "Polycube open source project";
   description "YANG data model for the Polycube Helloworld service";

  basemodel:service-description "Helloworld Service";
  basemodel:service-version "2.0";
  basemodel:service-name "helloworld";
  basemodel:service-min-kernel-version "4.14.0";

  uses "basemodel:base-yang-module";

  leaf action {
    type enumeration {
      enum DROP;
      enum SLOWPATH;
      enum FORWARD;
    }
    default DROP;
    description "Action performed on the received packet (i.e., DROP, SLOWPATH, or FORWARD; default: DROP)";
  }
}

)POLYCUBE_DM";

extern "C" const char *data_model() {
  return SERVICE_DATA_MODEL.c_str();
}


#include <polycube/services/shared_library.h>
