/**
* ddosmitigator API
* DDoS Mitigator Service
*
* OpenAPI spec version: 2.0
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/polycube-network/swagger-codegen.git
* branch polycube
*/


/* Do not edit this file manually */

#include "api/DdosmitigatorApiImpl.h"
#define MANAGER_TYPE io::swagger::server::api::DdosmitigatorApiImpl
#define SERVICE_DESCRIPTION "DDoS Mitigator Service"
#define SERVICE_VERSION "2.0"
#define SERVICE_PYANG_GIT ""
#define SERVICE_SWAGGER_CODEGEN_GIT "c757d44b71d48df9e381fc8d35ea69bd12268127/c757d44"
#define SERVICE_REQUIRED_KERNEL_VERSION "4.14.0"

const std::string SERVICE_DATA_MODEL = R"POLYCUBE_DM(
module ddosmitigator {
  yang-version 1.1;
  namespace "http://polycube.network/ddosmitigator";
  prefix "ddosmitigator";

  import polycube-base { prefix "basemodel"; }

  organization "Polycube open source project";
  description "YANG data model for the Polycube DDoS Mitigator service";

  basemodel:service-description "DDoS Mitigator Service";
  basemodel:service-version "2.0";
  basemodel:service-name "ddosmitigator";
  basemodel:service-min-kernel-version "4.14.0";

  uses "basemodel:base-yang-module";

  container stats {
    description "Statistics on dropped packets";
    config false;

    leaf pps {
      type uint64;
      config false;
      description "Dropped Packets/s";
    }

    leaf pkts {
      type uint64;
      config false;
      description "Total Dropped Packets";
    }
  }

  leaf active-port {
    type string;
    description "Port where the traffic is received";
  }

  leaf redirect-port {
    type string;
    description "If set, this will be the port used to redirect traffic (instead of PASS it to STACK)";
  }

  list blacklist-src {
      key "ip";
      description "Blacklisted source IP addresses";

      leaf ip {
        type string;
        description "Source IP Address";
        basemodel:cli-example "10.0.0.1";
      }

      leaf drop-pkts {
        type uint64;
        config false;
        description "Dropped Packets";
      }
  }

  list blacklist-dst {
      key "ip";
      description "Blacklisted destination IP addresses";

      leaf ip {
        type string;
        description "Destination IP Address";
        basemodel:cli-example "10.0.0.2";
      }

      leaf drop-pkts {
        type uint64;
        config false;
        description "Dropped Packets";
      }
  }
}

)POLYCUBE_DM";

extern "C" const char *data_model() {
  return SERVICE_DATA_MODEL.c_str();
}


#include <polycube/services/shared_library.h>
